spring:
  datasource: 
    url: jdbc:postgresql://localhost:5432/ecommercebd
    username: ecommerce
    password: ecommerce
    driver-class-name: org.postgresql.Driver
  jpa: 
    hibernate:
      ddl-auto: validate
    show-sql: true
    generate-ddl: true
server:
  port: 7002